In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# Testing locate point routine

## test 1

In [4]:
testr = np.linspace(0,10,11, dtype=np.float64)
testtheta = np.linspace(0,np.pi,11, dtype=np.float64)
testphi = np.linspace(0,2*np.pi,11, dtype=np.float64)
print("grid data:")
print("r values : {}".format(testr))
print("theta values : {}".format(testtheta))
print("phi values : {}".format(testphi))

x = 0.5196152422706632
y = 0.5196152422706632
z = 0.5196152422706632
print("point to locate (cartesian): {} {} {}".format(x,y,z))
def cartesiantospherical(x, y, z):
    r = np.sqrt(x**2 + y**2 + z**2)
    theta = np.arccos(z/r)
    phi = np.arccos(z/r)
    return r, theta, phi

r, t, p = cartesiantospherical(x, y, z)
print("point to locate (spherical): {} {} {}".format(r, t, p))
testcombs = [[np.float64(0),np.float64(0),np.float64(0)]]
for t in testtheta[3:5]:
    for p in testphi[1:3]:
        testcombs.append([np.float64(1), t, p])
print("surrounding points:")
print(np.array(testcombs))

grid data:
r values : [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
theta values : [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]
phi values : [0.         0.62831853 1.25663706 1.88495559 2.51327412 3.14159265
 3.76991118 4.39822972 5.02654825 5.65486678 6.28318531]
point to locate (cartesian): 0.5196152422706632 0.5196152422706632 0.5196152422706632
point to locate (spherical): 0.9000000000000001 0.9553166181245093 0.9553166181245093
surrounding points:
[[0.         0.         0.        ]
 [1.         0.9424778  0.62831853]
 [1.         0.9424778  1.25663706]
 [1.         1.25663706 0.62831853]
 [1.         1.25663706 1.25663706]]


In [5]:
def locate_point(
    r_arr, theta_arr, phi_arr, p
):  # r_arr, theta_arr, phi_arr define the ID grid, p defines a point in the new grid
    # p should be a tuple (x,y,z) in cartesian coords
    x, y, z = p
    r_0 = np.sqrt(x**2 + y**2 + z**2)
    theta_0 = np.arccos(z / r_0)
    phi_0 = np.arctan2(y, x)
    phi_0 = phi_0 % (2 * np.pi)  # ensures phi takes values between [0,2pi]
    rs, ts, ps = None, None, None

    for i in range(len(r_arr) - 1):
        if r_arr[i] <= r_0 <= r_arr[i + 1]:
            rs = (r_arr[i], r_arr[i + 1])
            break
    for i in range(len(theta_arr) - 1):
        if theta_arr[i] <= theta_0 <= theta_arr[i + 1]:
            ts = (theta_arr[i], theta_arr[i + 1])
            break
    for i in range(len(phi_arr) - 1):
        if phi_arr[i] <= phi_0 <= phi_arr[i + 1]:
            ps = (phi_arr[i], phi_arr[i + 1])
            break

    if rs is None or ts is None or ps is None:
        return None

    combinations = []
    if rs[0] == np.float64(0):
        combinations.append([np.float64(0), np.float64(0), np.float64(0)])
        for t in ts:
            for p in ps:
                combinations.append([rs[1], t, p])
    else:
        for r in rs:
            for t in ts:
                for p in ps:
                    combinations.append([r, t, p])

    return np.array(combinations)

In [6]:
testpoint = x, y, z

In [7]:
combs = locate_point(testr, testtheta, testphi, testpoint)

In [8]:
combs

array([[0.        , 0.        , 0.        ],
       [1.        , 0.9424778 , 0.62831853],
       [1.        , 0.9424778 , 1.25663706],
       [1.        , 1.25663706, 0.62831853],
       [1.        , 1.25663706, 1.25663706]])

In [9]:
np.array(testcombs)

array([[0.        , 0.        , 0.        ],
       [1.        , 0.9424778 , 0.62831853],
       [1.        , 0.9424778 , 1.25663706],
       [1.        , 1.25663706, 0.62831853],
       [1.        , 1.25663706, 1.25663706]])

## test 2

In [10]:
testr = np.linspace(0,10,11, dtype=np.float64)
testtheta = np.linspace(0,np.pi,11, dtype=np.float64)
testphi = np.linspace(0,2*np.pi,11, dtype=np.float64)
print("grid data:")
print("r values : {}".format(testr))
print("theta values : {}".format(testtheta))
print("phi values : {}".format(testphi))

x = np.float64(3)
y = np.float64(2.2)
z = np.float64(1.37)
print("point to locate (cartesian): {} {} {}".format(x,y,z))
def cartesiantospherical(x, y, z):
    r = np.sqrt(x**2 + y**2 + z**2)
    theta = np.arccos(z/r)
    phi = np.arccos(z/r)
    return r, theta, phi

r, t, p = cartesiantospherical(x, y, z)
print("point to locate (spherical): {} {} {}".format(r, t, p))

grid data:
r values : [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
theta values : [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]
phi values : [0.         0.62831853 1.25663706 1.88495559 2.51327412 3.14159265
 3.76991118 4.39822972 5.02654825 5.65486678 6.28318531]
point to locate (cartesian): 3.0 2.2 1.37
point to locate (spherical): 3.964454565258631 1.2179492645832868 1.2179492645832868


In [11]:
print(testr[3:5])
print(testtheta[3:5])
print(testphi[3:5])

[3. 4.]
[0.9424778  1.25663706]
[1.88495559 2.51327412]


In [12]:
testcombs2 = []
for r in testr[3:5]:
    for t in testtheta[3:5]:
        for p in testphi[3:5]:
            testcombs2.append([r, t, p])

In [13]:
np.array(testcombs2)

array([[3.        , 0.9424778 , 1.88495559],
       [3.        , 0.9424778 , 2.51327412],
       [3.        , 1.25663706, 1.88495559],
       [3.        , 1.25663706, 2.51327412],
       [4.        , 0.9424778 , 1.88495559],
       [4.        , 0.9424778 , 2.51327412],
       [4.        , 1.25663706, 1.88495559],
       [4.        , 1.25663706, 2.51327412]])

In [14]:
combs2 = locate_point(testr, testtheta, testphi, (x, y, z))

In [15]:
print(combs2)

[[3.         0.9424778  0.62831853]
 [3.         0.9424778  1.25663706]
 [3.         1.25663706 0.62831853]
 [3.         1.25663706 1.25663706]
 [4.         0.9424778  0.62831853]
 [4.         0.9424778  1.25663706]
 [4.         1.25663706 0.62831853]
 [4.         1.25663706 1.25663706]]


# test interpolation_point function

In [16]:
def calc_weighted_average(points, scalar_values, p):
    p = np.array(p)
    d = np.sum((points - p) ** 2, axis=1)
    weights = 1.0 / (d + 1e-6) ** 2

    if np.any(d <= 1e-6):
        return scalar_values[np.argmin(d)]

    return np.sum(weights * scalar_values) / np.sum(weights)

def interpolate_point(p, df, rad_arr, theta_arr, phi_arr, idx_point_map):
    num_scalars = len(df.columns) - 3
    surrounding_pts = locate_point(rad_arr, theta_arr, phi_arr, p)

    if surrounding_pts is None:
        raise ValueError("point p is outside grid domain")

    points = np.empty((len(surrounding_pts), 3))
    scalars = np.empty((len(surrounding_pts), num_scalars))

    for i, point in enumerate(surrounding_pts):
        r, t, p = point
        index = idx_point_map[(r, t, p)]
        if index is None:
            raise ValueError("point p is outside grid domain")
        closestrow = df.iloc[index]
        points[i] = spherical2cart(
            closestrow.iloc[0], closestrow.iloc[1], closestrow.iloc[2]
        )
        scalars[i] = closestrow[3:].values

    interpolatedvals = np.array(
        [calc_weighted_average(points, scalars[:, j], p) for j in range(num_scalars)]
    )
    return interpolatedvals

In [17]:
r_arr = np.linspace(0, 100, 100, dtype=np.float64)
t_arr = np.linspace(0, np.pi, 100, dtype=np.float64)
p_arr = np.linspace(0, 2*np.pi, 100, dtype=np.float64)
gridpoint = np.array(np.meshgrid(r_arr, t_arr, p_arr)).T.reshape(-1, 3)
df = pd.DataFrame(gridpoint, columns = ["r", "theta", "phi"])
df

r     theta       phi
0         0.0  0.000000  0.000000
1         0.0  0.031733  0.000000
2         0.0  0.063467  0.000000
3         0.0  0.095200  0.000000
4         0.0  0.126933  0.000000
...       ...       ...       ...
999995  100.0  3.014660  6.283185
999996  100.0  3.046393  6.283185
999997  100.0  3.078126  6.283185
999998  100.0  3.109859  6.283185
999999  100.0  3.141593  6.283185

[1000000 rows x 3 columns]

In [18]:
df["Z(r,t,p)"] = df.r * np.cos(df.theta)

In [19]:
df["Y(r,t,p)"] = df.r*np.sin(df.theta)*np.sin(df.phi)

In [20]:
df["X(r,t,p)"] = df.r*np.sin(df.theta)*np.cos(df.phi)

In [21]:
df

r     theta       phi    Z(r,t,p)      Y(r,t,p)      X(r,t,p)
0         0.0  0.000000  0.000000    0.000000  0.000000e+00  0.000000e+00
1         0.0  0.031733  0.000000    0.000000  0.000000e+00  0.000000e+00
2         0.0  0.063467  0.000000    0.000000  0.000000e+00  0.000000e+00
3         0.0  0.095200  0.000000    0.000000  0.000000e+00  0.000000e+00
4         0.0  0.126933  0.000000    0.000000  0.000000e+00  0.000000e+00
...       ...       ...       ...         ...           ...           ...
999995  100.0  3.014660  6.283185  -99.195481 -3.100621e-15  1.265925e+01
999996  100.0  3.046393  6.283185  -99.547192 -2.328202e-15  9.505604e+00
999997  100.0  3.078126  6.283185  -99.798668 -1.553438e-15  6.342392e+00
999998  100.0  3.109859  6.283185  -99.949654 -7.771102e-16  3.172793e+00
999999  100.0  3.141593  6.283185 -100.000000 -2.999520e-30  1.224647e-14

[1000000 rows x 6 columns]

In [22]:
def locate_point(
    r_arr, theta_arr, phi_arr, p
):  # r_arr, theta_arr, phi_arr define the ID grid, p defines a point in the new grid
    # p should be a tuple (x,y,z) in cartesian coords
    x, y, z = p
    r_0 = np.sqrt(x**2 + y**2 + z**2)
    theta_0 = np.arccos(z / r_0)
    phi_0 = np.arctan2(y, x)
    phi_0 = phi_0 % (2 * np.pi)  # ensures phi takes values between [0,2pi]
    rs, ts, ps = None, None, None

    for i in range(len(r_arr) - 1):
        if r_arr[i] <= r_0 <= r_arr[i + 1]:
            rs = (r_arr[i], r_arr[i + 1])
            break
    for i in range(len(theta_arr) - 1):
        if theta_arr[i] <= theta_0 <= theta_arr[i + 1]:
            ts = (theta_arr[i], theta_arr[i + 1])
            break
    for i in range(len(phi_arr) - 1):
        if phi_arr[i] <= phi_0 <= phi_arr[i + 1]:
            ps = (phi_arr[i], phi_arr[i + 1])
            break

    if rs is None or ts is None or ps is None:
        return None

    combinations = []
    if rs[0] == np.float64(0):
        combinations.append([np.float64(0), np.float64(0), np.float64(0)])
        for t in ts:
            for p in ps:
                combinations.append([rs[1], t, p])
    else:
        for r in rs:
            for t in ts:
                for p in ps:
                    combinations.append([r, t, p])

    return np.array(combinations)
    
# https://en.wikipedia.org/wiki/Inverse_distance_weighting
def calc_weighted_average(points, scalar_values, p):
    # points should be a numpy array
    # Compute distances from each point to p
    # Compute weights (inverse distances)
    #    weights = 1.0 / distances
    p = np.array(p)
    d = np.sum((points - p) ** 2, axis=1)
    weights = 1.0 / ((d + 1e-6) ** 2)

    if np.any(d <= 1e-6):
        return scalar_values[np.argmin(d)]

    return np.sum(weights * scalar_values) / np.sum(weights)

def spherical2cart(r, t, p):
    x = r * np.sin(t) * np.cos(p)
    y = r * np.sin(t) * np.sin(p)
    z = r * np.cos(t)
    return (x, y, z)


# data = load_3d_data('3D_data/ext_cur.3d')
def interpolate_point(p, df, rad_arr, theta_arr, phi_arr, idx_point_map):
    num_scalars = len(df.columns) - 3
    surrounding_pts = locate_point(rad_arr, theta_arr, phi_arr, p)

    if surrounding_pts is None:
        raise ValueError("point p is outside grid domain")

    points = np.empty((len(surrounding_pts), 3))
    scalars = np.empty((len(surrounding_pts), num_scalars))

    for i, point in enumerate(surrounding_pts):
        r, t, p = point
        index = idx_point_map[(r, t, p)]
        if index is None:
            raise ValueError("point p is outside grid domain")
        closestrow = df.iloc[index]
        points[i] = spherical2cart(
            closestrow.iloc[0], closestrow.iloc[1], closestrow.iloc[2]
        )
        scalars[i] = closestrow[3:].values

    interpolatedvals = np.array(
        [calc_weighted_average(points, scalars[:, j], p) for j in range(num_scalars)]
    )
    return interpolatedvals

In [23]:
rad_arr = np.sort(df.r.unique())
theta_arr = np.sort(df.theta.unique())
phi_arr = np.sort(df.phi.unique())
idx_point_map = {
    (r, theta, phi): index
    for index, (r, theta, phi) in enumerate(zip(df["r"], df["theta"], df["phi"]))
}

In [24]:
points = np.array([
    np.array([0.4, 0.2, 0.5]),
    np.array([14, 1/5, 1/9]),
    np.array([12.1, 7*np.pi/4, 9*np.pi/11]),
])

In [25]:
locate_point(rad_arr, theta_arr, phi_arr, points[1])

array([[13.13131313,  1.5549297 ,  0.        ],
       [13.13131313,  1.5549297 ,  0.06346652],
       [13.13131313,  1.58666296,  0.        ],
       [13.13131313,  1.58666296,  0.06346652],
       [14.14141414,  1.5549297 ,  0.        ],
       [14.14141414,  1.5549297 ,  0.06346652],
       [14.14141414,  1.58666296,  0.        ],
       [14.14141414,  1.58666296,  0.06346652]])

In [26]:
interpolate_point(points[2], df, rad_arr, theta_arr, phi_arr, idx_point_map)

array([ 2.56597803,  5.33525682, 12.18837909])

In [27]:
d = []
for p in points:
    d.append(interpolate_point(p, df, rad_arr, theta_arr, phi_arr, idx_point_map))

In [28]:
d = np.array(d)

In [31]:
d

array([[7.58149860e-01, 3.04897315e-01, 5.84051412e-01],
       [6.45243986e-05, 4.30263490e-01, 1.35463350e+01],
       [2.56597803e+00, 5.33525682e+00, 1.21883791e+01]])

In [33]:
points

array([[ 0.4       ,  0.2       ,  0.5       ],
       [14.        ,  0.2       ,  0.11111111],
       [12.1       ,  5.49778714,  2.57039399]])

In [34]:
newd = np.hstack((points, d))

In [2]:
ddf = pd.DataFrame(d, columns=["x", "y", "z", "var1", "var2", "var3"])

NameError: name 'pd' is not defined

In [35]:
newd

array([[4.00000000e-01, 2.00000000e-01, 5.00000000e-01, 7.58149860e-01,
        3.04897315e-01, 5.84051412e-01],
       [1.40000000e+01, 2.00000000e-01, 1.11111111e-01, 6.45243986e-05,
        4.30263490e-01, 1.35463350e+01],
       [1.21000000e+01, 5.49778714e+00, 2.57039399e+00, 2.56597803e+00,
        5.33525682e+00, 1.21883791e+01]])

In [36]:
a = np.linspace(1, 4, 3)

In [37]:
a

array([1. , 2.5, 4. ])

In [38]:
b = np.linspace(300, 400, 20)

In [39]:
b

array([300.        , 305.26315789, 310.52631579, 315.78947368,
       321.05263158, 326.31578947, 331.57894737, 336.84210526,
       342.10526316, 347.36842105, 352.63157895, 357.89473684,
       363.15789474, 368.42105263, 373.68421053, 378.94736842,
       384.21052632, 389.47368421, 394.73684211, 400.        ])

In [40]:
np.hstack((a,b))

array([  1.        ,   2.5       ,   4.        , 300.        ,
       305.26315789, 310.52631579, 315.78947368, 321.05263158,
       326.31578947, 331.57894737, 336.84210526, 342.10526316,
       347.36842105, 352.63157895, 357.89473684, 363.15789474,
       368.42105263, 373.68421053, 378.94736842, 384.21052632,
       389.47368421, 394.73684211, 400.        ])

In [43]:
a = [1, 2, 3]
b = [i for i in range(10, 40, 2)]

In [48]:
a + b[3:]

[1, 2, 3, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]