In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import KDTree

In [87]:
df_3d = pd.read_hdf("/data/sjammi6/thesisproject/BlackHoleDiskProject/InitialData/routine2/data/3D_data/all_data_routine1.h5", key="df")
df_3d

r     theta       phi     alpha   beta__x  beta__y  beta__z  \
0         0.300000  0.000000  0.000000  0.000000 -0.234914      0.0      0.0   
1         0.300000  0.000000  0.062832  0.000000 -0.234914      0.0      0.0   
2         0.300000  0.000000  0.125664  0.000000 -0.234914      0.0      0.0   
3         0.300000  0.000000  0.188496  0.000000 -0.234914      0.0      0.0   
4         0.300000  0.000000  0.251327  0.000000 -0.234914      0.0      0.0   
...            ...       ...       ...       ...       ...      ...      ...   
64600896  0.000052  1.573296  6.031858 -0.999101  0.000000      0.0      0.0   
64600897  0.000052  1.573296  6.094690 -0.999101  0.000000      0.0      0.0   
64600898  0.000052  1.573296  6.157522 -0.999101  0.000000      0.0      0.0   
64600899  0.000052  1.573296  6.220353 -0.999101  0.000000      0.0      0.0   
64600900  0.000000  0.000000  0.000000 -1.000000  0.000000      0.0      0.0   

               psi        gxx           gxy  ...           Kyy  Kyz  Kzz  rho  \
0         2.453739  36.250454  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   
1         2.453739  36.250454  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   
2         2.453739  36.250454  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   
3         2.453739  36.250454  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   
4         2.453739  36.250454  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   
...            ...        ...           ...  ...           ...  ...  ...  ...   
64600896  1.000450   1.001799  1.456307e-07  ...  2.624713e-10  0.0  0.0  0.0   
64600897  1.000450   1.001799  1.112814e-07  ...  1.511192e-10  0.0  0.0  0.0   
64600898  1.000450   1.001799  7.517719e-08  ...  0.000000e+00  0.0  0.0  0.0   
64600899  1.000450   1.001799  3.788735e-08  ...  0.000000e+00  0.0  0.0  0.0   
64600900  1.000000   1.000000  0.000000e+00  ...  0.000000e+00  0.0  0.0  0.0   

          u__x  u__y  u__z           A_x           A_y  A_z  
0          0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  
1          0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  
2          0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  
3          0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  
4          0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  
...        ...   ...   ...           ...           ...  ...  
64600896  -0.0  -0.0   0.0 -8.924000e-08 -3.475668e-07  0.0  
64600897  -0.0  -0.0   0.0 -6.724000e-08 -3.524844e-07  0.0  
64600898  -0.0  -0.0   0.0 -4.497464e-08 -3.560109e-07  0.0  
64600899  -0.0  -0.0   0.0 -2.253178e-08 -3.581324e-07  0.0  
64600900   0.0   0.0   0.0  0.000000e+00  0.000000e+00  0.0  

[64600901 rows x 27 columns]

In [4]:
pdata = df_3d[["r", "theta", "phi"]].values

In [5]:
type(pdata)

numpy.ndarray

In [8]:
pdata.dtype

dtype('float64')

In [37]:

def f(x, y, z):
    return np.array(
        [
            np.exp(-x**2) * y * z
#            x[0]*x[1]*x[2],
#            np.sin(x[0]) + np.cos(x[1]),
        ]
    )
def g(x, y, z):
    return np.array(
        [
#            np.exp(-x[0]**2),
            x*y*z
#            np.sin(x[0]) + np.cos(x[1]),
        ]
    )

def h(x, y, z):
    return np.array(
        [
#            np.exp(-x[0]**2),
#            x[0]*x[1]*x[2],
            np.sin(x) + np.cos(y)*z,
        ]
    )

In [4]:
x = np.linspace(0, 100, 101)
y = np.linspace(0, 100, 101)
z = np.linspace(-100, 100, 101)
grid = np.array(np.meshgrid(x, y, z)).T.reshape(-1, 3)

In [3]:
df_grid = pd.DataFrame(grid, columns=["x", "y", "z"])
df_grid["f"] = np.cos(df_grid.x) * np.sin(df_grid.y) * df_grid.z
df_grid["g"] = df_grid.x * df_grid.y * df_grid.z
df_grid["h"] = np.sin(df_grid.x) + np.cos(df_grid.y) * df_grid.z
df_grid

x      y      z          f          g           h
0          0.0    0.0 -100.0  -0.000000       -0.0 -100.000000
1          0.0    1.0 -100.0 -84.147098       -0.0  -54.030231
2          0.0    2.0 -100.0 -90.929743       -0.0   41.614684
3          0.0    3.0 -100.0 -14.112001       -0.0   98.999250
4          0.0    4.0 -100.0  75.680250       -0.0   65.364362
...        ...    ...    ...        ...        ...         ...
1030296  100.0   96.0  100.0  84.816628   960000.0  -18.549411
1030297  100.0   97.0  100.0  32.734292   970000.0  -93.021119
1030298  100.0   98.0  100.0 -49.443801   980000.0  -82.435190
1030299  100.0   99.0  100.0 -86.163491   990000.0    3.475722
1030300  100.0  100.0  100.0 -43.664865  1000000.0   85.725522

[1030301 rows x 6 columns]

In [5]:
tdata = KDTree(grid)

In [29]:
dis[0]

array([0.        , 1.        , 1.        , 1.        , 1.        ,
       1.41421356, 1.41421356, 1.41421356])

In [6]:
dis, ind = tdata.query([[8, 12, 14], [2, 4, 19]], k=8)

In [46]:
df_grid.iloc[ind[0]]

x     y     z          f       g          h
582277  8.0  12.0  14.0   1.092999  1344.0  12.803314
582276  8.0  11.0  14.0   2.036981  1232.0   1.051318
582378  9.0  12.0  14.0   6.844430  1512.0  12.226074
582176  7.0  12.0  14.0  -5.663329  1176.0  12.470942
582278  8.0  13.0  14.0  -0.855880  1456.0  13.693613
582177  7.0  13.0  14.0   4.434708  1274.0  13.361242
582175  7.0  11.0  14.0 -10.554528  1078.0   0.718946
582377  9.0  11.0  14.0  12.755699  1386.0   0.474078

In [26]:
nn = [grid[i] for i in ind[0]]
nn

[array([ 8., 12., 14.]),
 array([ 8., 11., 14.]),
 array([ 9., 12., 14.]),
 array([ 7., 12., 14.]),
 array([ 8., 13., 14.]),
 array([ 7., 13., 14.]),
 array([ 7., 11., 14.]),
 array([ 9., 11., 14.])]

In [50]:
def process_line(line):
    parts = line.split()[1:]  # Ignore the first column
    new_grid = list(map(np.float64, parts))
    output_file = f"CTS_bin-proc{parts[-1]}.d"     
    return new_grid, output_file


In [51]:
grids_filepath =  "/data/sjammi6/thesisproject/BlackHoleDiskProject/InitialData/routine2/grids_bh_disk_patrik"
linedata = []
with open(grids_filepath, "r") as f:
    lines = f.readlines()
    linedata = [process_line(line) for line in lines]

In [52]:
linedata[0]

([np.float64(198.401),
  np.float64(64.00000000000004),
  np.float64(396.8),
  np.float64(6.4),
  np.float64(6.4),
  np.float64(6.4),
  np.float64(41.0),
  np.float64(37.0),
  np.float64(39.0),
  np.float64(-979427380.0)],
 'CTS_bin-proc-979427380.d')

In [20]:
dis[0]

array([0.        , 1.        , 1.        , 1.        , 1.        ,
       1.41421356, 1.41421356, 1.41421356])

In [15]:
np.array(df_grid.iloc[ind[0][3]].values[3:])

array([  -5.66332946, 1176.        ,   12.47094202])

In [17]:
t = df_grid.iloc[ind[0][3]]
p = [np.float64(8), np.float64(12), np.float64(14)]

In [18]:
np.hstack([p, t.values[3:]])

array([   8.        ,   12.        ,   14.        ,   -5.66332946,
       1176.        ,   12.47094202])

In [52]:
weights = dis[0].reshape((-1, 1))
scalarvals = df_grid.iloc[ind[0]].values
print(scalarvals[:, 3:].shape)
print(weights.shape)
r = weights * scalarvals[:, 3:]
print(r)
print(r.shape)

(8, 3)
(8, 1)
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.03698052e+00  1.23200000e+03  1.05131802e+00]
 [ 6.84442953e+00  1.51200000e+03  1.22260739e+01]
 [-5.66332946e+00  1.17600000e+03  1.24709420e+01]
 [-8.55880453e-01  1.45600000e+03  1.36936132e+01]
 [ 6.27162458e+00  1.80170808e+03  1.88956490e+01]
 [-1.49263569e+01  1.52452222e+03  1.01674371e+00]
 [ 1.80392822e+01  1.96010000e+03  6.70447901e-01]]
(8, 3)


In [44]:
scalarvals[:, 3:]

array([[ 1.09299929e+00,  1.34400000e+03,  1.28033137e+01],
       [ 2.03698052e+00,  1.23200000e+03,  1.05131802e+00],
       [ 6.84442953e+00,  1.51200000e+03,  1.22260739e+01],
       [-5.66332946e+00,  1.17600000e+03,  1.24709420e+01],
       [-8.55880453e-01,  1.45600000e+03,  1.36936132e+01],
       [ 4.43470827e+00,  1.27400000e+03,  1.33612415e+01],
       [-1.05545282e+01,  1.07800000e+03,  7.18946371e-01],
       [ 1.27556987e+01,  1.38600000e+03,  4.74078257e-01]])

In [33]:
weights

array([[0.        , 1.        , 1.        , 1.        , 1.        ,
        1.41421356, 1.41421356, 1.41421356]])

In [34]:
scalarvals

array([[ 8.00000000e+00,  1.20000000e+01,  1.40000000e+01,
         1.09299929e+00,  1.34400000e+03,  1.28033137e+01],
       [ 8.00000000e+00,  1.10000000e+01,  1.40000000e+01,
         2.03698052e+00,  1.23200000e+03,  1.05131802e+00],
       [ 9.00000000e+00,  1.20000000e+01,  1.40000000e+01,
         6.84442953e+00,  1.51200000e+03,  1.22260739e+01],
       [ 7.00000000e+00,  1.20000000e+01,  1.40000000e+01,
        -5.66332946e+00,  1.17600000e+03,  1.24709420e+01],
       [ 8.00000000e+00,  1.30000000e+01,  1.40000000e+01,
        -8.55880453e-01,  1.45600000e+03,  1.36936132e+01],
       [ 7.00000000e+00,  1.30000000e+01,  1.40000000e+01,
         4.43470827e+00,  1.27400000e+03,  1.33612415e+01],
       [ 7.00000000e+00,  1.10000000e+01,  1.40000000e+01,
        -1.05545282e+01,  1.07800000e+03,  7.18946371e-01],
       [ 9.00000000e+00,  1.10000000e+01,  1.40000000e+01,
         1.27556987e+01,  1.38600000e+03,  4.74078257e-01]])

In [53]:
r = np.sum(r, axis=0)

In [57]:
np.sum(weights)

np.float64(8.242640687119286)

In [56]:
weights

array([[0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.41421356],
       [1.41421356],
       [1.41421356]])

In [58]:
r/np.sum(weights)

array([   1.42511974, 1293.55757468,    7.28222787])

In [55]:
np.sum(weights)

np.float64(8.242640687119286)

In [103]:
tmpx = np.arange(12, 22, 1)
tmpy = np.arange(32, 44, 1)
tmpz = np.arange(54, 82, 1)
tmp_pdata = np.array(np.meshgrid(tmpx, tmpy, tmpz)).T.reshape(-1, 3)

In [105]:
tmp_pdata

array([[12, 32, 54],
       [12, 33, 54],
       [12, 34, 54],
       ...,
       [21, 41, 81],
       [21, 42, 81],
       [21, 43, 81]])

In [108]:
dMat, iMat = tdata.query(tmp_pdata, k=8, workers=-1)

In [71]:
print(dMat.shape)
print(iMat.shape)
print(tmp_pdata.shape)

(4, 8)
(4, 8)
(4, 3)


In [75]:
cols = list(df_grid.columns)
cols

['x', 'y', 'z', 'f', 'g', 'h']

In [127]:
df_grid.iloc[iMat[:, 0][:5]].values

array([[ 1.20000000e+01,  3.20000000e+01,  5.40000000e+01,
         2.51274737e+01,  2.07360000e+04,  4.45114885e+01],
       [ 1.20000000e+01,  3.30000000e+01,  5.40000000e+01,
         4.55640974e+01,  2.13840000e+04, -1.25351727e+00],
       [ 1.20000000e+01,  3.40000000e+01,  5.40000000e+01,
         2.41093000e+01,  2.20320000e+04, -4.63593678e+01],
       [ 1.20000000e+01,  3.50000000e+01,  5.40000000e+01,
        -1.95114766e+01,  2.26800000e+04, -4.93359520e+01],
       [ 1.20000000e+01,  3.60000000e+01,  5.40000000e+01,
        -4.51934916e+01,  2.33280000e+04, -7.44661216e+00]])

In [128]:
print(tmp_pdata.shape[0])
print(df_grid.shape[1])
#resMat = np.zeros((tmp_pdata.shape[0], df_grid.shape[1]))
#resMat.shape
resMat = np.where(dMat[:, 0][:, np.newaxis] == 0, df_grid.iloc[iMat[:, 0]].values, np.zeros((len(dMat),6)))


3360
6


In [129]:
resMat

array([[ 1.20000000e+01,  3.20000000e+01,  5.40000000e+01,
         2.51274737e+01,  2.07360000e+04,  4.45114885e+01],
       [ 1.20000000e+01,  3.30000000e+01,  5.40000000e+01,
         4.55640974e+01,  2.13840000e+04, -1.25351727e+00],
       [ 1.20000000e+01,  3.40000000e+01,  5.40000000e+01,
         2.41093000e+01,  2.20320000e+04, -4.63593678e+01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [76]:
def interpolate_grid(p, dist, ind, df):
    if np.any(dist == 0):
        t = df.iloc[ind[np.argmin(dist)]]
        return np.hstack([p, t.values[3:]])
    w = 1/dist
    w = w.reshape((-1, 1))
    r = np.sum(w * df.iloc[ind].values[:, 3:], axis=0) / np.sum(w)
    return np.hstack([p, r])

In [109]:
interpolated_data = np.array([interpolate_grid(p, d, i, df_grid) for p, d, i in zip(tmp_pdata, dMat, iMat)])

In [110]:
interpolated_data[:, :3]

array([[12., 32., 54.],
       [12., 33., 54.],
       [12., 34., 54.],
       ...,
       [21., 41., 81.],
       [21., 42., 81.],
       [21., 43., 81.]])

In [91]:
cols = ["x", "y", "z", "f", "g", "h"]

In [95]:
df = pd.DataFrame(columns=cols)

In [96]:
tmp_df = pd.DataFrame(interpolated_data, columns=cols)

In [94]:
df = pd.concat([df, tmp_df], ignore_index=True)

/tmp/ipykernel_1321288/1314517867.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, tmp_df], ignore_index=True)


In [99]:
df = pd.concat([df, tmp_df], axis=0, ignore_index=True)


In [100]:
df

x     y     z          f        g          h
0  12.0  32.0  54.0  25.127474  20736.0  44.511489
1  20.0  32.0  54.0  12.151476  34560.0  45.961007
2  12.0  32.0  68.0  31.642004  26112.0  56.190616
3  20.0  32.0  68.0  15.301859  43520.0  57.640134
4  12.0  32.0  54.0  25.127474  20736.0  44.511489
5  20.0  32.0  54.0  12.151476  34560.0  45.961007
6  12.0  32.0  68.0  31.642004  26112.0  56.190616
7  20.0  32.0  68.0  15.301859  43520.0  57.640134

In [130]:
resMat

array([[ 1.20000000e+01,  3.20000000e+01,  5.40000000e+01,
         2.51274737e+01,  2.07360000e+04,  4.45114885e+01],
       [ 1.20000000e+01,  3.30000000e+01,  5.40000000e+01,
         4.55640974e+01,  2.13840000e+04, -1.25351727e+00],
       [ 1.20000000e+01,  3.40000000e+01,  5.40000000e+01,
         2.41093000e+01,  2.20320000e+04, -4.63593678e+01],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [136]:
nonzeroresMax = np.all(resMat != 0, axis=1)
resMax_nonzero = resMat[nonzeroresMax]


In [141]:
newdMat = dMat[~nonzeroresMax]
wMat = 1/newdMat
newiMat = iMat[~nonzeroresMax]
new_pdata = tmp_pdata[~nonzeroresMax]
for i in range(len(newdMat)):
    r = np.sum(wMat[i].reshape((-1, 1)) * df_grid.iloc[newiMat[i]].values[:, 3:], axis=0) / np.sum(wMat[i])
    resMax_nonzero = np.vstack([resMax_nonzero, np.hstack([new_pdata[i], r])])


In [138]:
rahh = np.linspace(1, 25, 25).reshape((5,5))
rahh

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [139]:
rahh = 1/rahh

In [140]:
d = 

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.04761905, 0.04545455, 0.04347826, 0.04166667, 0.04      ]])

In [142]:
rahh.reshape(-1, 1)

array([[1.        ],
       [0.5       ],
       [0.33333333],
       [0.25      ],
       [0.2       ],
       [0.16666667],
       [0.14285714],
       [0.125     ],
       [0.11111111],
       [0.1       ],
       [0.09090909],
       [0.08333333],
       [0.07692308],
       [0.07142857],
       [0.06666667],
       [0.0625    ],
       [0.05882353],
       [0.05555556],
       [0.05263158],
       [0.05      ],
       [0.04761905],
       [0.04545455],
       [0.04347826],
       [0.04166667],
       [0.04      ]])

In [147]:
rahh[0].reshape((-1, 1)) * np.arange(1, 6)

array([[1.        , 2.        , 3.        , 4.        , 5.        ],
       [0.5       , 1.        , 1.5       , 2.        , 2.5       ],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [0.25      , 0.5       , 0.75      , 1.        , 1.25      ],
       [0.2       , 0.4       , 0.6       , 0.8       , 1.        ]])

In [148]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])