In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
df = pd.read_hdf("/data/sjammi6/thesisproject/updates/BlackHoleDiskProject/InitialData/routine1/October_15_2024_22-05/3D_data/all_data_routine1.h5", key="df")
df

r     theta       phi     alpha       beta__x       beta__y  \
0         0.300000  0.000000  0.000000  0.000000 -2.349142e-01  0.000000e+00   
1         0.300000  0.000000  0.063467  0.000000 -2.349142e-01  0.000000e+00   
2         0.300000  0.000000  0.126933  0.000000 -2.349142e-01  0.000000e+00   
3         0.300000  0.000000  0.190400  0.000000 -2.349142e-01  0.000000e+00   
4         0.300000  0.000000  0.253866  0.000000 -2.349142e-01  0.000000e+00   
...            ...       ...       ...       ...           ...           ...   
64600896  0.000052  1.573296  6.092786 -0.999101  2.903060e-12  6.689876e-13   
64600897  0.000052  1.573296  6.156252 -0.999101  2.903060e-12  6.689876e-13   
64600898  0.000052  1.573296  6.219719 -0.999101  2.903060e-12  6.689876e-13   
64600899  0.000052  1.573296  6.283185 -0.999101  2.903060e-12  6.689876e-13   
64600900  0.000000  0.000000  0.000000  1.000000  0.000000e+00  0.000000e+00   

          beta__z       psi        gxx           gxy  ...           Kyy  \
0            -0.0  2.453739  36.250454  0.000000e+00  ...  0.000000e+00   
1            -0.0  2.453739  36.250454  0.000000e+00  ...  0.000000e+00   
2            -0.0  2.453739  36.250454  0.000000e+00  ...  0.000000e+00   
3            -0.0  2.453739  36.250454  0.000000e+00  ...  0.000000e+00   
4            -0.0  2.453739  36.250454  0.000000e+00  ...  0.000000e+00   
...           ...       ...        ...           ...  ...           ...   
64600896     -0.0  1.000450   1.001799  1.123509e-07  ...  1.540942e-10   
64600897     -0.0  1.000450   1.001799  7.592026e-08  ...  6.965242e-11   
64600898     -0.0  1.000450   1.001799  3.826800e-08  ...  1.758975e-11   
64600899     -0.0  1.000450   1.001799  1.480808e-22  ... -1.982074e-37   
64600900      0.0  1.000000   1.000000  0.000000e+00  ...  0.000000e+00   

                   Kyz  Kzz  rho  u__x  u__y  u__z           A_x  \
0         0.000000e+00  0.0  0.0   0.0  -0.0   0.0  0.000000e+00   
1         0.000000e+00  0.0  0.0   0.0  -0.0   0.0  0.000000e+00   
2         0.000000e+00  0.0  0.0   0.0  -0.0   0.0  0.000000e+00   
3         0.000000e+00  0.0  0.0   0.0  -0.0   0.0  0.000000e+00   
4         0.000000e+00  0.0  0.0   0.0  -0.0   0.0  0.000000e+00   
...                ...  ...  ...   ...   ...   ...           ...   
64600896 -5.377990e-12  0.0  0.0   0.0   0.0  -0.0 -6.791101e-08   
64600897 -5.432903e-12  0.0  0.0   0.0   0.0  -0.0 -4.542650e-08   
64600898 -5.465939e-12  0.0  0.0   0.0   0.0  -0.0 -2.275907e-08   
64600899 -5.476966e-12  0.0  0.0   0.0   0.0  -0.0 -8.789057e-23   
64600900  0.000000e+00  0.0  0.0   0.0   0.0   0.0  0.000000e+00   

                   A_y  A_z  
0         0.000000e+00  0.0  
1         0.000000e+00  0.0  
2         0.000000e+00  0.0  
3         0.000000e+00  0.0  
4         0.000000e+00  0.0  
...                ...  ...  
64600896 -3.523558e-07  0.0  
64600897 -3.559535e-07  0.0  
64600898 -3.581180e-07  0.0  
64600899 -3.588405e-07  0.0  
64600900  0.000000e+00  0.0  

[64600901 rows x 27 columns]

In [55]:
rad_arr = np.sort(df.r.unique())
theta_arr = np.sort(df.theta.unique())
phi_arr = np.sort(df.phi.unique())
idx_point_map = {
    (r, theta, phi): index
    for index, (r, theta, phi) in enumerate(zip(df["r"], df["theta"], df["phi"]))
}

In [53]:

def locate_point(
    r_arr, theta_arr, phi_arr, p
):  # r_arr, theta_arr, phi_arr define the ID grid, p defines a point in the new grid
    # p should be a tuple (x,y,z) in cartesian coords
    x, y, z = p
    r_0 = np.sqrt(x**2 + y**2 + z**2)
    theta_0 = np.arccos(z / r_0)
    phi_0 = np.arctan2(y, x)
    phi_0 = phi_0 % (2 * np.pi)  # ensures phi takes values between [0,2pi]
    rs, ts, ps = None, None, None

    for i in range(len(r_arr) - 1):
        if r_arr[i] <= r_0 <= r_arr[i + 1]:
            rs = (r_arr[i], r_arr[i + 1])
            break
    for i in range(len(theta_arr) - 1):
        if theta_arr[i] <= theta_0 <= theta_arr[i + 1]:
            ts = (theta_arr[i], theta_arr[i + 1])
            break
    for i in range(len(phi_arr) - 1):
        if phi_arr[i] <= phi_0 <= phi_arr[i + 1]:
            ps = (phi_arr[i], phi_arr[i + 1])
            break

    if rs is None or ts is None or ps is None:
        return None

    combinations = []
    if rs[0] == np.float64(0):
        combinations.append([np.float64(0), np.float64(0), np.float64(0)])
        for t in ts:
            for p in ps:
                combinations.append([rs[1], t, p])
    else:
        for r in rs:
            for t in ts:
                for p in ps:
                    combinations.append([r, t, p])
    print("==========================================================")
    print("THE FOLLOWING ARE SURROUNDING POINTS FOR ({},{},{})".format(x,y,z))
    for c in combinations:
        print(c)
    print("==========================================================")
    return np.array(combinations)

In [65]:
def calc_weighted_average(points, scalar_vals, p):
    d = np.sum((points - p) ** 2, axis=1)
    if any(d <= 1e-4):
        print("found point in og grid") 
        return scalar_vals[np.argmin(d)]
    weights = 1 / ((d) ** 2)
    weights = weights.reshape((-1, 1))
    print("==========================================================")
    print("calc_weighted_average calculations")
    print("point p")
    print(p)
    print("----------------")
    print("scalar values")
    print(scalar_vals[:, 6])
    print("----------------")
    print("distance")
    print(d)
    print("----------------")
    print("weights")
    print(weights)
    print("----------------")
    print("interpolated point:")
    print(np.sum(weights * scalar_vals, axis=0) / np.sum(weights))
    print("==========================================================")
    return np.sum(weights * scalar_vals, axis=0) / np.sum(weights)

In [66]:
def spherical2cart(r, t, p):
    x = r * np.sin(t) * np.cos(p)
    y = r * np.sin(t) * np.sin(p)
    z = r * np.cos(t)
    return (x, y, z)

In [67]:
def interpolate_point(p, df, rad_arr, theta_arr, phi_arr, idx_point_map):
    surroundingpoints = locate_point(rad_arr, theta_arr, phi_arr, p)  # numpy array
    carpointdata = []
    scalardata = []
    for point in surroundingpoints:
        tmpr, tmpt, tmpp = point
        rowIndex = idx_point_map[(tmpr, tmpt, tmpp)]
        rowdata = df.iloc[rowIndex]
        tmpx, tmpy, tmpz = spherical2cart(tmpr, tmpt, tmpp)
        carpointdata.append([tmpx, tmpy, tmpz])
        scalardata.append(rowdata[3:])
    carpointdata = np.array(carpointdata)
    print("==========================================================")
    print("carpointdata")
    print(carpointdata)
    print(carpointdata.shape)
    print("==========================================================")
    print("scalar point data")
    scalardata = np.array(scalardata)
    print(scalardata)
    print(scalardata.shape)
    print("==========================================================")
    interpolateddata = calc_weighted_average(carpointdata, scalardata, p)
    return np.hstack((p, interpolateddata))

In [68]:
tmp = interpolate_point((0.4128, 0, 0), df, rad_arr, theta_arr, phi_arr, idx_point_map)

THE FOLLOWING ARE SURROUNDING POINTS FOR (0.4128,0,0)
[np.float64(0.4105826588237613), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(0.4105826588237613), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(0.4105826588237613), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(0.4105826588237613), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
[np.float64(0.4176884854119989), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(0.4176884854119989), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(0.4176884854119989), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(0.4176884854119989), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
carpointdata
[[4.10581376e-01 0.00000000e+00 1.02645665e-03]
 [4.09754743e-01 2.60406802e-02 1.02645665e-03]
 [4.10582659e-01 0.00000000e+00 2.51409369e-17]
 [4.09756023e-01 2.60407616e-02 2.51409369e-17]
 [4.17687180e-01 0.00

In [69]:
tmp = interpolate_point((0.213500, 0, 0), df, rad_arr, theta_arr, phi_arr, idx_point_map)

THE FOLLOWING ARE SURROUNDING POINTS FOR (0.2135,0,0)
[np.float64(0.21183180908255148), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(0.21183180908255148), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(0.21183180908255148), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(0.21183180908255148), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
[np.float64(0.2154715850287947), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(0.2154715850287947), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(0.2154715850287947), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(0.2154715850287947), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
carpointdata
[[2.11831147e-01 0.00000000e+00 5.29579523e-04]
 [2.11404662e-01 1.34351617e-02 5.29579523e-04]
 [2.11831809e-01 0.00000000e+00 1.29709573e-17]
 [2.11405323e-01 1.34352036e-02 1.29709573e-17]
 [2.15470912e-01 

In [80]:
import os
import pathlib 
dataframes = []
for f in pathlib.Path("/data/sjammi6/thesisproject/updates/BlackHoleDiskProject/InitialData/routine1/October_15_2024_22-05/processed_grids/dataframes").glob("*.h5"):
    dataframes.append(str(f))
dataframes = [pd.read_hdf(f, key="df") for f in dataframes]
df_interpolated = pd.concat(dataframes, axis=0, ignore_index=True)
df_interpolated_xplanev2 = df_interpolated[
    (df_interpolated.y >= np.float64(-0.0001)) & 
    (df_interpolated.y <= np.float64(0.0001)) & 
    (df_interpolated.z >= np.float64(-0.0001)) & 
    (df_interpolated.z <= np.float64(0.0001))
]

df_interpolated_xplanev2 = df_interpolated_xplanev2.sort_values(['x', 'y', 'z'])
df_nonzerogxy_interpolated_data = df_interpolated_xplanev2[(df_interpolated_xplanev2.gxy <= -1e-7) | (df_interpolated_xplanev2.gxy >= 1e-7)]
df_nonzerogxy_interpolated_data.sort_values(by=['x', 'y', 'z'])
df_nonzerogxy_interpolated_dataxvals = df_nonzerogxy_interpolated_data[df_nonzerogxy_interpolated_data.x >= np.float64(0)]
xvals = np.array(df_nonzerogxy_interpolated_dataxvals.x.unique())

In [91]:
random_points = np.random.choice(xvals, size=3, replace=False)
random_points

array([2.226 , 0.276 , 0.7885])

In [95]:
for p in random_points:
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    tmp = interpolate_point((p, 0, 0), df, rad_arr, theta_arr, phi_arr, idx_point_map)


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
THE FOLLOWING ARE SURROUNDING POINTS FOR (2.2260000000000106,0,0)
[np.float64(2.2143693561605), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(2.2143693561605), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(2.2143693561605), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(2.2143693561605), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
[np.float64(2.2395130497221047), np.float64(1.5682963241907226), np.float64(0.0)]
[np.float64(2.2395130497221047), np.float64(1.5682963241907226), np.float64(0.06346651825433926)]
[np.float64(2.2395130497221047), np.float64(1.5707963267948966), np.float64(0.0)]
[np.float64(2.2395130497221047), np.float64(1.5707963267948966), np.float64(0.06346651825433926)]
carpointdata
[[2.21436244e+00 0.00000000e+00 5.53592339e-03]
 [2.20990421e+00 1.40443545e-01 5.53592339e-03]
 [2.21436936e+00 0.00000000e+00 1.35591017e-16]
 [2.20991111e+00 1

In [96]:
df_3Dalldata_100k = pd.read_hdf("/data/sjammi6/thesisproject/updates/BlackHoleDiskProject/InitialData/routine1/October_15_2024_22-05/3D_data/all_data_routine1.h5", key="df")

In [99]:
rvals = df_3Dalldata_100k.r.unique()

In [101]:
rvals = np.sort(rvals)
rvals[1]

np.float64(5.184965998340518e-05)