In [1]:
import pandas as pd
import numpy as np

In [4]:
cgrids = np.loadtxt("/home/shreyjam/scratch/research/thesis/BlackHoleDiskProject/src/initialdata/cartesian_coords.txt")
cgrids

array([[1., 4., 5.],
       [1., 4., 6.],
       [1., 4., 7.],
       [1., 4., 8.],
       [1., 5., 5.],
       [1., 5., 6.],
       [1., 5., 7.],
       [1., 5., 8.],
       [1., 6., 5.],
       [1., 6., 6.],
       [1., 6., 7.],
       [1., 6., 8.],
       [1., 7., 5.],
       [1., 7., 6.],
       [1., 7., 7.],
       [1., 7., 8.]])

In [5]:
sgrid = np.loadtxt("/home/shreyjam/scratch/research/thesis/BlackHoleDiskProject/src/initialdata/spherical_coords.txt")
sgrid

array([[ 6.480741 ,  0.6895746,  1.325818 ],
       [ 7.28011  ,  0.6020729,  1.325818 ],
       [ 8.124038 ,  0.5323032,  1.325818 ],
       [ 9.       ,  0.4758822,  1.325818 ],
       [ 7.141428 ,  0.7952027,  1.373401 ],
       [ 7.874008 ,  0.7043992,  1.373401 ],
       [ 8.660254 ,  0.6295537,  1.373401 ],
       [ 9.486833 ,  0.5674505,  1.373401 ],
       [ 7.874008 ,  0.882787 ,  1.405648 ],
       [ 8.544004 ,  0.7922477,  1.405648 ],
       [ 9.273618 ,  0.7154023,  1.405648 ],
       [10.04988  ,  0.6500893,  1.405648 ],
       [ 8.660254 ,  0.9553166,  1.428899 ],
       [ 9.273618 ,  0.8671574,  1.428899 ],
       [ 9.949874 ,  0.7904488,  1.428899 ],
       [10.67708  ,  0.7238393,  1.428899 ]])

In [6]:
def cartesiantospherical(arr):
    r = np.sqrt(arr[:, 0]**2 + arr[:, 1]**2 + arr[:, 2]**2)
    theta = np.where(r != 0.0, np.arccos(np.clip(arr[:, 2] / r, -1.0, 1.0)), 0.0)
    phi = np.arctan2(arr[:, 1], arr[:, 0])
    new_grid = np.column_stack((r, theta, phi))
    new_grid = np.where(abs(new_grid) < 1e-14, np.float64(0), new_grid)
    return new_grid


In [7]:
tmpsgrid = cartesiantospherical(cgrids)

In [8]:
tmpsgrid

array([[ 6.4807407 ,  0.68957457,  1.32581766],
       [ 7.28010989,  0.60207292,  1.32581766],
       [ 8.1240384 ,  0.5323032 ,  1.32581766],
       [ 9.        ,  0.47588225,  1.32581766],
       [ 7.14142843,  0.79520271,  1.37340077],
       [ 7.87400787,  0.70439919,  1.37340077],
       [ 8.66025404,  0.62955368,  1.37340077],
       [ 9.48683298,  0.56745048,  1.37340077],
       [ 7.87400787,  0.88278698,  1.40564765],
       [ 8.54400375,  0.79224769,  1.40564765],
       [ 9.2736185 ,  0.71540232,  1.40564765],
       [10.04987562,  0.6500893 ,  1.40564765],
       [ 8.66025404,  0.95531662,  1.42889927],
       [ 9.2736185 ,  0.86715738,  1.42889927],
       [ 9.94987437,  0.79044875,  1.42889927],
       [10.67707825,  0.72383925,  1.42889927]])

In [9]:
tmpsgrid - sgrid

array([[-3.01592140e-07, -3.40902598e-08, -3.36331967e-07],
       [-1.10719482e-07,  2.02613331e-08, -3.36331967e-07],
       [ 4.04635960e-07,  3.58414665e-09, -3.36331967e-07],
       [ 0.00000000e+00,  4.96604167e-08, -3.36331967e-07],
       [ 4.28542850e-07,  1.32896781e-08, -2.33054984e-07],
       [-1.25988189e-07, -1.38881144e-08, -2.33054984e-07],
       [ 3.78443872e-08, -2.33184507e-08, -2.33054984e-07],
       [-1.94948626e-08, -2.47211629e-08, -2.33054984e-07],
       [-1.25988189e-07, -1.52353749e-08, -3.50619730e-07],
       [-2.54682469e-07, -7.30082172e-09, -3.50619730e-07],
       [ 4.95495703e-07,  1.95202120e-08, -3.50619730e-07],
       [-4.37887911e-06,  1.00656261e-10, -3.50619730e-07],
       [ 3.78443872e-08,  1.81245093e-08,  2.72190733e-07],
       [ 4.95495703e-07, -2.45098386e-08,  2.72190733e-07],
       [ 3.71066200e-07, -4.56639238e-08,  2.72190733e-07],
       [-1.74796869e-06, -4.58456690e-08,  2.72190733e-07]])